
version: '3.5'
services:

  database:

    image: "postgres:latest"

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    
    volumes:
      - spacex_table.sql:/docker-entrypoint-initdb.d/create_tables.sql